/**
 * 
 */
package com.i2r.ARC.PCControl.link.BluetoothLink;

/**
 * This object encapsulates the events generated by the Bluetooth SDP protocol and completion
 *
 * @author Johnathan Pagnutti
 *
 */
public class BluetoothLinkEvent {
	//the transaction ID of the event
	private int transID;
	//the return code of the event
	private int code;
	
	/**
	 * Constructor
	 */
	public BluetoothLinkEvent(){}
	
	/**
	 * Set the transaction ID of this event
	 * 
	 * @param ID the transaction ID to set
	 */
	public void setTransID(int ID){
		transID = ID;
	}
	
	/**
	 * get the transaction ID of this event 
	 * 
	 * @requires that the transID has been set
	 * @returns the integer value transID
	 */
	public int getTransID(){
		return transID;
	}
	
	/**
	 * Set the code associated with this event
	 * 
	 * @param code the code to set
	 */
	public void setCode(int code){
		this.code = code;
	}
	
	/**
	 * Get the code associated with this event
	 * 
	 * @requires that code has been set
	 * @return the integer value code
	 */
	public int getCode(){
		return code;
	}
}
